const CDN = 'https://pub-0e3520b4da7b4fd383674dd5e967ed42.r2.dev';

const postcards = [
  {
    id: 1,
    author: 'Bbi',
    instagram: '@isooplll',
    instagramUrl: 'https://instagram.com/isooplll',
    image: `${CDN}/Bbi%201.png`,
    extras: [`${CDN}/Bbi%202.png`],
  },
  {
    id: 2,
    author: 'eugene',
    instagram: '@euxxgene_works',
    instagramUrl: 'https://instagram.com/euxxgene_works',
    image: `${CDN}/eugene%201.webp`,
    extras: [`${CDN}/eugene%202.webp`],
  },
  {
    id: 3,
    author: 'mana',
    instagram: '@mana.webp',
    instagramUrl: 'https://instagram.com/mana.webp',
    image: `${CDN}/mana%201.png`,
    extras: [`${CDN}/mana%202.png`],
  },
  {
    id: 4,
    author: 'soi',
    instagram: '@soiios.zz',
    instagramUrl: 'https://instagram.com/soiios.zz',
    image: `${CDN}/soi%201.jpg`,
    extras: [`${CDN}/soi%202.jpg`],
  },
  {
    id: 5,
    author: 'symsi',
    instagram: '@every.thing.is',
    instagramUrl: 'https://instagram.com/every.thing.is',
    image: `${CDN}/symsi.jpg`,
  },
  {
    id: 6,
    author: 'yyoung',
    instagram: '@yyoung200',
    instagramUrl: 'https://instagram.com/yyoung200',
    image: `${CDN}/yyoung.jpg`,
  },
  {
    id: 7,
    author: 'zooya kim',
    instagram: '@zooya_kim',
    instagramUrl: 'https://instagram.com/zooya_kim',
    image: `${CDN}/zooya%20kim%201.jpg`,
    extras: [`${CDN}/zooya%20kim%202.jpg`],
  },
  {
    id: 8,
    author: '곽예림',
    instagram: '@kwakk.yr',
    instagramUrl: 'https://instagram.com/kwakk.yr',
    image: `${CDN}/%E1%84%80%E1%85%AA%E1%86%A8%E1%84%8B%E1%85%A8%E1%84%85%E1%85%B5%E1%86%B7%201.jpg`,
    extras: [`${CDN}/%E1%84%80%E1%85%AA%E1%86%A8%E1%84%8B%E1%85%A8%E1%84%85%E1%85%B5%E1%86%B7%202.jpg`],
  },
  {
    id: 9,
    author: '구혜린',
    instagram: '@cm369yk',
    instagramUrl: 'https://instagram.com/cm369yk',
    image: `${CDN}/%E1%84%80%E1%85%AE%E1%84%92%E1%85%A8%E1%84%85%E1%85%B5%E1%86%AB.jpg`,
  },
  {
    id: 10,
    author: '김예경',
    instagram: '@yewrks',
    instagramUrl: 'https://instagram.com/yewrks',
    video: `${CDN}/%E1%84%80%E1%85%B5%E1%86%B7%E1%84%8B%E1%85%A8%E1%84%80%E1%85%A7%E1%86%BC.mp4`,
  },
  {
    id: 11,
    author: '바랑',
    instagram: '@barang._.design_',
    instagramUrl: 'https://instagram.com/barang._.design_',
    image: `${CDN}/%E1%84%87%E1%85%A1%E1%84%85%E1%85%A1%E1%86%BC%201.png`,
    extras: [`${CDN}/%E1%84%87%E1%85%A1%E1%84%85%E1%85%A1%E1%86%BC%202.png`],
  },
  {
    id: 12,
    author: '박베리',
    instagram: '@bahkberry_x',
    instagramUrl: 'https://instagram.com/bahkberry_x',
    image: `${CDN}/%E1%84%87%E1%85%A1%E1%86%A8%E1%84%87%E1%85%A6%E1%84%85%E1%85%B5%201.jpg`,
    extras: [`${CDN}/%E1%84%87%E1%85%A1%E1%86%A8%E1%84%87%E1%85%A6%E1%84%85%E1%85%B5%202.png`],
  },
  {
    id: 13,
    author: '방채연',
    instagram: '@_cha.archive.on',
    instagramUrl: 'https://instagram.com/_cha.archive.on',
    image: `${CDN}/%E1%84%87%E1%85%A1%E1%86%BC%E1%84%8E%E1%85%A2%E1%84%8B%E1%85%A7%E1%86%AB%201.jpg`,
    extras: [
      `${CDN}/%E1%84%87%E1%85%A1%E1%86%BC%E1%84%8E%E1%85%A2%E1%84%8B%E1%85%A7%E1%86%AB%202.jpg`,
      `${CDN}/%E1%84%87%E1%85%A1%E1%86%BC%E1%84%8E%E1%85%A2%E1%84%8B%E1%85%A7%E1%86%AB%203.jpg`,
      `${CDN}/%E1%84%87%E1%85%A1%E1%86%BC%E1%84%8E%E1%85%A2%E1%84%8B%E1%85%A7%E1%86%AB%204.jpg`,
    ],
  },
  {
    id: 14,
    author: '시나브',
    instagram: '@airdrop_1122',
    instagramUrl: 'https://instagram.com/airdrop_1122',
    image: `${CDN}/%E1%84%89%E1%85%B5%E1%84%82%E1%85%A1%E1%84%87%E1%85%B3.jpg`,
  },
  {
    id: 15,
    author: '시오',
    instagram: '@seao_zip',
    instagramUrl: 'https://instagram.com/seao_zip',
    image: `${CDN}/%E1%84%89%E1%85%B5%E1%84%8B%E1%85%A9%201.jpg`,
    extras: [`${CDN}/%E1%84%89%E1%85%B5%E1%84%8B%E1%85%A9%202.jpg`],
  },
  {
    id: 16,
    author: '신환준',
    instagram: '@seenhzn',
    instagramUrl: 'https://instagram.com/seenhzn',
    image: `${CDN}/%E1%84%89%E1%85%B5%E1%86%AB%E1%84%92%E1%85%AA%E1%86%AB%E1%84%8C%E1%85%AE%E1%86%AB.png`,
  },
  {
    id: 17,
    author: '오재',
    instagram: '@ojaeh.kr',
    instagramUrl: 'https://instagram.com/ojaeh.kr',
    image: `${CDN}/%E1%84%8B%E1%85%A9%E1%84%8C%E1%85%A2%201.png`,
    extras: [`${CDN}/%E1%84%8B%E1%85%A9%E1%84%8C%E1%85%A2%202.png`],
  },
  {
    id: 18,
    author: '유원',
    instagram: '@_deeef3',
    instagramUrl: 'https://instagram.com/_deeef3',
    image: `${CDN}/%E1%84%8B%E1%85%B2%E1%84%8B%E1%85%AF%E1%86%AB%201.jpg`,
    extras: [`${CDN}/%E1%84%8B%E1%85%B2%E1%84%8B%E1%85%AF%E1%86%AB%202.jpg`],
  },
  {
    id: 19,
    author: '이채현',
    instagram: '',
    instagramUrl: '',
    image: `${CDN}/%E1%84%8B%E1%85%B5%E1%84%8E%E1%85%A2%E1%84%92%E1%85%A7%E1%86%AB.jpg`,
  },
  {
    id: 20,
    author: '정현주',
    instagram: '@jujung.hyn',
    instagramUrl: 'https://instagram.com/jujung.hyn',
    image: `${CDN}/%E1%84%8C%E1%85%A5%E1%86%BC%E1%84%92%E1%85%A7%E1%86%AB%E1%84%8C%E1%85%AE.jpg`,
  },
  {
    id: 21,
    author: '최이안',
    instagram: '@ianch0i',
    instagramUrl: 'https://instagram.com/ianch0i',
    image: `${CDN}/%E1%84%8E%E1%85%AC%E1%84%8B%E1%85%B5%E1%84%8B%E1%85%A1%E1%86%AB.jpg`,
  },
  {
    id: 22,
    author: '피피',
    instagram: '@peepi.kr',
    instagramUrl: 'https://instagram.com/peepi.kr',
    image: `${CDN}/%E1%84%91%E1%85%B5%E1%84%91%E1%85%B5%201.png`,
    extras: [`${CDN}/%E1%84%91%E1%85%B5%E1%84%91%E1%85%B5%202.png`],
  },
  {
    id: 23,
    author: '희윤',
    instagram: '@hyoonzine',
    instagramUrl: 'https://instagram.com/hyoonzine',
    image: `${CDN}/%E1%84%92%E1%85%B4%E1%84%8B%E1%85%B2%E1%86%AB.png`,
  },
  {
    id: 24,
    author: '문채원',
    instagram: '@whatinthe_zip',
    instagramUrl: 'https://instagram.com/whatinthe_zip',
    image: `${CDN}/chaewon.jpg`,
  },
  {
    id: 25,
    author: 'seon',
    instagram: '@seon.object',
    instagramUrl: 'https://instagram.com/seon.object',
    image: `${CDN}/seon.jpg`,
  },
  {
    id: 26,
    author: '어랏',
    instagram: '@alolot.kr',
    instagramUrl: 'https://instagram.com/alolot.kr',
    image: `${CDN}/alot.jpg`,
    extras: [`${CDN}/alot2.jpg`],
  },
  {
    id: 27,
    author: '혜민',
    instagram: '@gingself04',
    instagramUrl: 'https://instagram.com/gingself04',
    image: `${CDN}/hyemin.png`,
  },
    {
    id: 28,
    author: '윤은정',
    instagram: '@yun.eun.jeong',
    instagramUrl: 'https://instagram.com/yun.eun.jeong',
    image: `${CDN}/eunjung.jpg`,
  },
      {
    id: 29,
    author: '해해',
    instagram: '',
    instagramUrl: '',
    image: `${CDN}/haehae.jpg`,
  },
  {
    id: 30,
    author: '이지현',
    instagram: '@lllieless',
    instagramUrl: 'https://instagram.com/lllieless',
    image: `${CDN}/jihyun_1.jpg`,
    extras: [
      `${CDN}/jihyun_2.jpg`,
      `${CDN}/jihyun_3.jpg`,
      `${CDN}/jihyun_4.jpg`,
    ],
  },
  {
    id: 31,
    author: '김민서',
    instagram: '@10000ans_w',
    instagramUrl: 'https://instagram.com/10000ans_w',
    image: `${CDN}/minseo_1.png`,
    extras: [
      `${CDN}/minseo_2.png`,
    ],
  },
    {
    id: 32,
    author: '김현아',
    instagram: '@_della.kim',
    instagramUrl: 'https://instagram.com/_della.kim',
    image: `${CDN}/hyuna.jpg`,
  },
      {
    id: 33,
    author: 'wltn',
    instagram: '',
    instagramUrl: '',
    image: `${CDN}/wltn.jpg`,
  },
  {
    id: 34,
    author: '수빈',
    instagram: '@znqoxls',
    instagramUrl: 'https://instagram.com/znqoxls',
    image: `${CDN}/subin_1.jpg`,
    extras: [
      `${CDN}/subin_2.jpg`,
    ],
  },
    {
    id: 35,
    author: 'Myaa',
    instagram: '@mayanpins',
    instagramUrl: 'https://instagram.com/mayanpins',
    image: `${CDN}/Myaa_1.png`,
    extras: [
      `${CDN}/Myaa_2.jpg`,
      `${CDN}/Myaa_3.jpg`,
    ],
  },
        {
    id: 36,
    author: '비비',
    instagram: '@bibiioxo',
    instagramUrl: 'https://instagram.com/bibiioxo',
    image: `${CDN}/bibi_1.jpg`,
    extras: [
      `${CDN}/bibi_2.jpg`,
    ],
  },
            {
    id: 37,
    author: '유쿠루',
    instagram: '@studio.ykr',
    instagramUrl: 'https://instagram.com/studio.ykr',
    image: `${CDN}/youkuru.jpg`,
  },
                {
    id: 38,
    author: '가현',
    instagram: '@pnk5_4',
    instagramUrl: 'https://instagram.com/pnk5_4',
    image: `${CDN}/kahyun_1.jpg`,
    extras: [
      `${CDN}/kahyun_1.jpg`,
    ],
  },
                                {
    id: 39,
    author: 'Songhee.jo',
    instagram: '@songhee.jo',
    instagramUrl: 'https://instagram.com/songhee.jo',
    image: `${CDN}/songhee.jpg`,
  },
                                                                {
    id: 40,
    author: '세이지',
    instagram: '@sageonpages',
    instagramUrl: 'https://instagram.com/sageonpages',
    image: `${CDN}/sage.jpg`,
  },
                                                                                                                                {
    id: 41,
    author: 'kolochae',
    instagram: '@kolochae_',
    instagramUrl: 'https://instagram.com/kolochae_',
    image: `${CDN}/kolochae.png`,
  },
                                                                                                                                                                                                                                                                {
    id: 42,
    author: '영',
    instagram: '',
    instagramUrl: '',
    image: `${CDN}/young.jpg`,
  },
    {
    id: 43,
    author: 'Asteroid',
    instagram: '@hr_pdf',
    instagramUrl: 'https://instagram.com/hr_pdf',
    image: `${CDN}/Asteroid_2.jpg`,
    extras: [
      `${CDN}/Asteroid_1.jpg`,
    ],
  },
      {
    id: 44,
    author: 'myjelobeads',
    instagram: '@myjelobeads',
    instagramUrl: 'https://instagram.com/myjelobeads',
    image: `${CDN}/myjelobeads.png`,
  },
  {
    id: 45,
    author: '잔',
    instagram: '@raiseyourjeanne',
    instagramUrl: 'https://instagram.com/raiseyourjeanne',
    image: `${CDN}/raiseyourjeanne_1.jpg`,
    extras: [
      `${CDN}/raiseyourjeanne_2.jpg`,
    ],
  },
    {
    id: 46,
    author: '댓마잼',
    instagram: '@that_ma_jam',
    instagramUrl: 'https://instagram.com/that_ma_jam',
    image: `${CDN}/that_ma_jam_1.jpg`,
    extras: [
      `${CDN}/that_ma_jam_2.jpg`,
    ],
  },
  {
    id: 47,
    author: '연',
    instagram: '@yyeonarc',
    instagramUrl: 'https://instagram.com/yyeonarc',
    image: `${CDN}/yyeonarc.png`,
  },
      {
    id: 48,
    author: '사연',
    instagram: '@2x2year',
    instagramUrl: 'https://instagram.com/2x2year',
    image: `${CDN}/2x2year.png`,
  },
          {
    id: 49,
    author: '소기박',
    instagram: '@wherecatshouldbe',
    instagramUrl: 'https://instagram.com/wherecatshouldbe',
    image: `${CDN}/wherecatshouldbe.jpg`,
  },
  {
    id: 50,
    author: '늘',
    instagram: '@neul.arc',
    instagramUrl: 'https://instagram.com/neul.arc',
    image: `${CDN}/neul.arc_1.jpg`,
    extras: [
      `${CDN}/neul.arc_2.jpg`,
    ],
  },
    {
    id: 51,
    author: '곽가영',
    instagram: '@i916you',
    instagramUrl: 'https://instagram.com/i916you',
    image: `${CDN}/i916you_1.png`,
    extras: [
      `${CDN}/i916you_2.png`,
    ],
  },
        {
    id: 52,
    author: '한이',
    instagram: '@han.ee.eo',
    instagramUrl: 'https://instagram.com/han.ee.eo',
    image: `${CDN}/haneeeo_1.jpg`,
    extras: [
      `${CDN}/haneeeo_2.jpg`,
    ],
  },
            {
    id: 53,
    author: '고민지',
    instagram: '@minjworks',
    instagramUrl: 'https://instagram.com/minjworks',
    image: `${CDN}/minjworks.jpeg`,
    extras: [
      `${CDN}/minjworks_1.jpg`,
    ],
  },
  {
    id: 54,
    author: '윤수영',
    instagram: '@swimy_graphics',
    instagramUrl: 'https://instagram.com/swimy_graphics',
    image: `${CDN}/swimy_graphics.jpg`,
  },
    {
    id: 55,
    author: 'CRI',
    instagram: '@c_user_cri',
    instagramUrl: 'https://instagram.com/c_user_cri',
    image: `${CDN}/c_user_cri.jpg`,
  },
  {
    id: 57,
    author: '콜로니',
    instagram: '@to.colony',
    instagramUrl: 'https://instagram.com/to.colony',
    image: `${CDN}/b0nbogi_1.jpg`,
    extras: [
      `${CDN}/b0nbogi_2.jpg`,
      `${CDN}/b0nbogi_3.jpg`,
      `${CDN}/b0nbogi_4.jpg`,
    ],
  },
  {
    id: 58,
    author: 'BON',
    instagram: '@b0n.bogi',
    instagramUrl: 'https://instagram.com/b0n.bogi',
    image: `${CDN}/tocolony.jpg`,
  },
  {
    id: 59,
    author: 'onzi',
    instagram: '@hjworksarchive',
    instagramUrl: 'https://instagram.com/hjworksarchive',
    image: `${CDN}/hjworksarchive_2.png`,
    extras: [
      `${CDN}/hjworksarchive_3.png`,
      `${CDN}/hjworksarchive_1.png`,
    ],
  },
  {
    id: 60,
    author: '이빈컵',
    instagram: '@leeemptycup',
    instagramUrl: 'https://instagram.com/leeemptycup',
    image: `${CDN}/leeemptycup_1.jpg`,
    extras: [
      `${CDN}/leeemptycup_2.jpg`,
    ],
  },
  {
    id: 61,
    author: '주',
    instagram: '@joo.keboxx',
    instagramUrl: 'https://instagram.com/joo.keboxx',
    image: `${CDN}/jookeboxx_1.png`,
    extras: [
      `${CDN}/jookeboxx_2.png`,
    ],
  },
  {
    id: 62,
    author: '배서연',
    instagram: '@baeseoye0n',
    instagramUrl: 'https://instagram.com/baeseoye0n',
    image: `${CDN}/baeseoye0n.png`,
  },
  {
    id: 63,
    author: 'mona',
    instagram: '@monauzys',
    instagramUrl: 'https://instagram.com/monauzys',
    image: `${CDN}/monauzys_1.jpg`,
    extras: [
      `${CDN}/monauzys_2.jpg`,
    ],
  },
  {
    id: 64,
    author: '이예원',
    instagram: '@nowey.works',
    instagramUrl: 'https://instagram.com/nowey.works',
    video: `${CDN}/noweyworks_1.mp4`,
    extras: [
      `${CDN}/noweyworks_2.png`,
      `${CDN}/noweyworks_3.png`,
    ],
  },
  {
    id: 65,
    author: '해파',
    instagram: '@heapa_s2',
    instagramUrl: 'https://instagram.com/heapa_s2',
    image: `${CDN}/heapa_s2.jpg`,
  },
  {
    id: 66,
    author: 'MiZi',
    instagram: '@lab.of.mizi',
    instagramUrl: 'https://instagram.com/lab.of.mizi',
    image: `${CDN}/labofmizi_1.png`,
    extras: [
      `${CDN}/labofmizi_2.png`,
    ],
  },
    {
    id: 67,
    author: 'RuU',
    instagram: '@hh_g4ru',
    instagramUrl: 'https://instagram.com/hh_g4ru',
    image: `${CDN}/hh_g4ru_1.png`,
    extras: [
      `${CDN}/hh_g4ru_2.png`,
    ],
  },
  {
    id: 68,
    author: '민',
    instagram: '@dicexotice',
    instagramUrl: 'https://instagram.com/dicexotice',
    image: `${CDN}/dicexotice.png`,
  },
  {
    id: 69,
    author: '장혜진',
    instagram: '@hve_zln.01',
    instagramUrl: 'https://instagram.com/hve_zln.01',
    image: `${CDN}/hve_zln_01.jpg`,
  },
      {
    id: 67,
    author: 'MUSEIN',
    instagram: '@kmusein',
    instagramUrl: 'https://instagram.com/kmusein',
    image: `${CDN}/kmusein.jpg`,
  },
  {
    id: 68,
    author: '김효빈',
    instagram: '@kimyobin_',
    instagramUrl: 'https://instagram.com/kimyobin_',
    image: `${CDN}/kimyobin_.jpg`,
  },
    {
    id: 69,
    author: '정세아',
    instagram: '@say__aaahhh',
    instagramUrl: 'https://instagram.com/say__aaahhh',
    image: `${CDN}/say__aaahhh_1.png`,
    extras: [
      `${CDN}/say__aaahhh_2.png`,
    ],
  },
        {
    id: 70,
    author: '아른',
    instagram: '@areun_030',
    instagramUrl: 'https://instagram.com/areun_030',
    image: `${CDN}/areun_030_1.jpg`,
    extras: [
      `${CDN}/areun_030_2.jpg`,
    ],
  },
];
